### ISSUE TITLE
bitcore-explorers is broken

### ISSUE THREAD

**Issue by smithb1994** [bitpay/bitcore-explorers#25]
Running from fresh npm gives me this error:

```
/node_modules/bitcore-explorers/node_modules/bitcore/index.js:12
    throw new Error(message);
    ^

Error: More than one instance of bitcore found with versions: v0.12.15 and v0.13.10. 
Please make sure to require bitcore and check that submodules do not also include 
their own bitcore dependency.
```

I think it has to do with the bitcore name change to bitcore-lib
**EDIT:** It looks like the npm package isn't up to date. Master is 1.0.1 and npm is still at 0.11.0

**Comment by braydonf** [comment]
bitcore-explorers is at 1.0.1 on npmjs here: https://www.npmjs.com/package/bitcore-explorers 

I've previously had issues with pulling in an older version and was cleared by using `npm cache clean` and updating `package.json`.
