### ISSUE TITLE
getUnspentUtxos is returning no result..

### ISSUE THREAD

**Issue by chano08** [bitpay/bitcore-explorers#33]
i have 2 utxos on my address with $20 and $25 amounts, then i spent $30 using that address and it uses the 2 utxos, transaction goes well(but still unconfirmed) but when i get the utxos using the bitcore-explorers getUnspentUtxos( ) it returns no result.. i also use the bitcore playground to get the uxtos of my address it returns none also... but when the transaction was CONFIRMED.. the amount that should be remaining on my address was there now, and the bitcore-explorers getUnspentUtxos( ) is returning result..

but then i tried it on single utxo with $50 amount and spend $10 and get the utxo after the transaction using bitcore-explorers getUnspentUtxos( ) and it returns result..

so the issue is, if an address has multiple utxos and if all utxos of the address was used in transaction, the supposed to be change output( change utxo ) is not being returned by getUnspentUtxos( ) until the transaction is CONFIRMED..

but this issue is not occuring when the address has single(1) utxo and was use in transaction.

also this issue is not occuring if there's a utxo that was not used in transaction..
like address have 3 utxos and only 2 was used..

any idea what cause this?

Thank you.

**Comment by braydonf** [comment]
Please do not ask [the same question](https://forum.bitcore.io/t/bitcore-explorers-getunspentutxos-returns-empty-result/919) on both the forum.bitcore.io and github issues.
- Github issues for reporting bugs and feature requests specific to the repository
- Forum is for support queries and general and higher level topics and discusssion
